/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StockLazyRicImport } from './routes/stock.lazy/$ric'

// Create/Update Routes

const StockLazyRicRoute = StockLazyRicImport.update({
  id: '/stock/lazy/$ric',
  path: '/stock/lazy/$ric',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/stock/lazy/$ric': {
      id: '/stock/lazy/$ric'
      path: '/stock/lazy/$ric'
      fullPath: '/stock/lazy/$ric'
      preLoaderRoute: typeof StockLazyRicImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/stock/lazy/$ric': typeof StockLazyRicRoute
}

export interface FileRoutesByTo {
  '/stock/lazy/$ric': typeof StockLazyRicRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/stock/lazy/$ric': typeof StockLazyRicRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/stock/lazy/$ric'
  fileRoutesByTo: FileRoutesByTo
  to: '/stock/lazy/$ric'
  id: '__root__' | '/stock/lazy/$ric'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  StockLazyRicRoute: typeof StockLazyRicRoute
}

const rootRouteChildren: RootRouteChildren = {
  StockLazyRicRoute: StockLazyRicRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/stock/lazy/$ric"
      ]
    },
    "/stock/lazy/$ric": {
      "filePath": "stock.lazy/$ric.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
